/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 * include/uapi/linux/ethtool_netlink.h - netlink interface for ethtool
 *
 * See Documentation/networking/ethtool-netlink.txt in kernel source tree for
 * doucumentation of the interface.
 */

#ifndef _UAPI_LINUX_ETHTOOL_NETLINK_H_
#define _UAPI_LINUX_ETHTOOL_NETLINK_H_

#include <linux/ethtool.h>

enum {
	ETHNL_CMD_NOOP,
	ETHNL_CMD_EVENT,		/* only for notifications */
	ETHNL_CMD_GET_STRSET,
	ETHNL_CMD_SET_STRSET,		/* only for reply */
	ETHNL_CMD_GET_INFO,
	ETHNL_CMD_SET_INFO,		/* only for reply */
	ETHNL_CMD_GET_SETTINGS,
	ETHNL_CMD_SET_SETTINGS,
	ETHNL_CMD_GET_PARAMS,
	ETHNL_CMD_SET_PARAMS,
	ETHNL_CMD_ACT_NWAY_RST,
	ETHNL_CMD_ACT_PHYS_ID,
	ETHNL_CMD_ACT_RESET,
	ETHNL_CMD_GET_RXFLOW,
	ETHNL_CMD_SET_RXFLOW,
	ETHNL_CMD_ACT_CABLE_TEST,

	__ETHNL_CMD_CNT,
	ETHNL_CMD_MAX = (__ETHNL_CMD_CNT - 1)
};

/* device specification */

enum {
	ETHTOOL_A_DEV_UNSPEC,
	ETHTOOL_A_DEV_INDEX,			/* u32 */
	ETHTOOL_A_DEV_NAME,			/* string */

	__ETHTOOL_A_DEV_CNT,
	ETHTOOL_A_DEV_MAX = (__ETHTOOL_A_DEV_CNT - 1)
};

/* bit sets */

enum {
	ETHTOOL_A_BIT_UNSPEC,
	ETHTOOL_A_BIT_INDEX,			/* u32 */
	ETHTOOL_A_BIT_NAME,			/* string */
	ETHTOOL_A_BIT_VALUE,			/* flag */

	__ETHTOOL_A_BIT_CNT,
	ETHTOOL_A_BIT_MAX = (__ETHTOOL_A_BIT_CNT - 1)
};

enum {
	ETHTOOL_A_BITS_UNSPEC,
	ETHTOOL_A_BITS_BIT,

	__ETHTOOL_A_BITS_CNT,
	ETHTOOL_A_BITS_MAX = (__ETHTOOL_A_BITS_CNT - 1)
};

enum {
	ETHTOOL_A_BITSET_UNSPEC,
	ETHTOOL_A_BITSET_LIST,			/* flag */
	ETHTOOL_A_BITSET_SIZE,			/* u32 */
	ETHTOOL_A_BITSET_BITS,			/* nest - ETHTOOL_A_BITS_* */
	ETHTOOL_A_BITSET_VALUE,			/* binary */
	ETHTOOL_A_BITSET_MASK,			/* binary */

	__ETHTOOL_A_BITSET_CNT,
	ETHTOOL_A_BITSET_MAX = (__ETHTOOL_A_BITSET_CNT - 1)
};

/* events */

enum {
	ETHTOOL_A_NEWDEV_UNSPEC,
	ETHTOOL_A_NEWDEV_DEV,			/* nest - ETHTOOL_A_DEV_* */

	__ETHTOOL_A_NEWDEV_CNT,
	ETHTOOL_A_NEWDEV_MAX = (__ETHTOOL_A_NEWDEV_CNT - 1)
};

enum {
	ETHTOOL_A_DELDEV_UNSPEC,
	ETHTOOL_A_DELDEV_DEV,			/* nest - ETHTOOL_A_DEV_* */

	__ETHTOOL_A_DELDEV_CNT,
	ETHTOOL_A_DELDEV_MAX = (__ETHTOOL_A_DELDEV_CNT - 1)
};

enum {
	ETHTOOL_A_RENAMEDEV_UNSPEC,
	ETHTOOL_A_RENAMEDEV_DEV,		/* nest - ETHTOOL_A_DEV_* */

	__ETHTOOL_A_RENAMEDEV_CNT,
	ETHTOOL_A_RENAMEDEV_MAX = (__ETHTOOL_A_RENAMEDEV_CNT - 1)
};

enum {
	ETHTOOL_A_EVENT_UNSPEC,
	ETHTOOL_A_EVENT_NEWDEV,			/* nest - ETHTOOL_A_NEWDEV_* */
	ETHTOOL_A_EVENT_DELDEV,			/* nest - ETHTOOL_A_DELDEV_* */
	ETHTOOL_A_EVENT_RENAMEDEV,		/* nest - ETHTOOL_A_RENAMEDEV_* */
	ETHTOOL_A_EVENT_CABLE_TEST,		/* nest - ETHTOOL_A_CABLE_TEST_* */

	__ETHTOOL_A_EVENT_CNT,
	ETHTOOL_A_EVENT_MAX = (__ETHTOOL_A_EVENT_CNT - 1)
};

/* string sets */

enum {
	ETHTOOL_A_STRING_UNSPEC,
	ETHTOOL_A_STRING_INDEX,			/* u32 */
	ETHTOOL_A_STRING_VALUE,			/* string */

	__ETHTOOL_A_STRING_CNT,
	ETHTOOL_A_STRING_MAX = (__ETHTOOL_A_STRING_CNT - 1)
};

enum {
	ETHTOOL_A_STRINGS_UNSPEC,
	ETHTOOL_A_STRINGS_STRING,		/* nest - ETHTOOL_A_STRINGS_* */

	__ETHTOOL_A_STRINGS_CNT,
	ETHTOOL_A_STRINGS_MAX = (__ETHTOOL_A_STRINGS_CNT - 1)
};

enum {
	ETHTOOL_A_STRINGSET_UNSPEC,
	ETHTOOL_A_STRINGSET_ID,			/* u32 */
	ETHTOOL_A_STRINGSET_COUNT,		/* u32 */
	ETHTOOL_A_STRINGSET_STRINGS,		/* nest - ETHTOOL_A_STRINGS_* */

	__ETHTOOL_A_STRINGSET_CNT,
	ETHTOOL_A_STRINGSET_MAX = (__ETHTOOL_A_STRINGSET_CNT - 1)
};

/* GET_STRINGSET / SET_STRINGSET */

enum {
	ETHTOOL_A_STRSET_UNSPEC,
	ETHTOOL_A_STRSET_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_STRSET_COUNTS,		/* flag */
	ETHTOOL_A_STRSET_STRINGSET,		/* nest - ETHTOOL_A_STRSET_* */

	__ETHTOOL_A_STRSET_CNT,
	ETHTOOL_A_STRSET_MAX = (__ETHTOOL_A_STRSET_CNT - 1)
};

/* GET_INFO / SET_INFO */

enum {
	ETHTOOL_A_INFO_UNSPEC,
	ETHTOOL_A_INFO_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_INFO_INFOMASK,		/* u32 */
	ETHTOOL_A_INFO_COMPACT,			/* flag */
	ETHTOOL_A_INFO_DRVINFO,			/* nest - ETHTOOL_A_DRVINFO_* */
	ETHTOOL_A_INFO_TSINFO,			/* nest - ETHTOOL_A_TSINFO_* */

	__ETHTOOL_A_INFO_CNT,
	ETHTOOL_A_INFO_MAX = (__ETHTOOL_A_INFO_CNT - 1)
};

#define ETHTOOL_IM_INFO_DRVINFO			(1U << 0)
#define ETHTOOL_IM_INFO_TSINFO			(1U << 1)

#define ETHTOOL_IM_INFO_ALL (ETHTOOL_IM_INFO_DRVINFO | \
			     ETHTOOL_IM_INFO_TSINFO)

enum {
	ETHTOOL_A_DRVINFO_UNSPEC,
	ETHTOOL_A_DRVINFO_DRIVER,		/* string */
	ETHTOOL_A_DRVINFO_FWVERSION,		/* string */
	ETHTOOL_A_DRVINFO_BUSINFO,		/* string */
	ETHTOOL_A_DRVINFO_EROM_VER,		/* string */

	__ETHTOOL_A_DRVINFO_CNT,
	ETHTOOL_A_DRVINFO_MAX = (__ETHTOOL_A_DRVINFO_CNT - 1)
};

enum {
	ETHTOOL_A_TSINFO_UNSPEC,
	ETHTOOL_A_TSINFO_TIMESTAMPING,		/* bitset */
	ETHTOOL_A_TSINFO_PHC_INDEX,		/* u32 */
	ETHTOOL_A_TSINFO_TX_TYPES,		/* bitset */
	ETHTOOL_A_TSINFO_RX_FILTERS,		/* bitset */

	__ETHTOOL_A_TSINFO_CNT,
	ETHTOOL_A_TSINFO_MAX = (__ETHTOOL_A_TSINFO_CNT - 1)
};

/* GET_SETTINGS / SET_SETTINGS */

enum {
	ETHTOOL_A_SETTINGS_UNSPEC,
	ETHTOOL_A_SETTINGS_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_SETTINGS_INFOMASK,		/* u32 */
	ETHTOOL_A_SETTINGS_COMPACT,		/* flag */
	ETHTOOL_A_SETTINGS_LINK_INFO,		/* nest - ETHTOOL_A_LINKINFO_* */
	ETHTOOL_A_SETTINGS_LINK_MODES,		/* nest - ETHTOOL_A_LINKMODES_* */
	ETHTOOL_A_SETTINGS_LINK_STATE,		/* nest - ETHTOOL_A_LINKSTATE_* */
	ETHTOOL_A_SETTINGS_WOL,			/* nest - ETHTOOL_A_WOL_* */
	ETHTOOL_A_SETTINGS_DEBUG,		/* nest - ETHTOOL_A_DEBUG_* */
	ETHTOOL_A_SETTINGS_FEATURES,		/* nest - ETHTOOL_A_FEATURES_* */
	ETHTOOL_A_SETTINGS_PRIV_FLAGS,		/* bitset */

	__ETHTOOL_A_SETTINGS_CNT,
	ETHTOOL_A_SETTINGS_MAX = (__ETHTOOL_A_SETTINGS_CNT - 1)
};

#define ETHTOOL_IM_SETTINGS_LINKINFO		(1U << 0)
#define ETHTOOL_IM_SETTINGS_LINKMODES		(1U << 1)
#define ETHTOOL_IM_SETTINGS_LINKSTATE		(1U << 2)
#define ETHTOOL_IM_SETTINGS_WOL			(1U << 3)
#define ETHTOOL_IM_SETTINGS_DEBUG		(1U << 4)
#define ETHTOOL_IM_SETTINGS_FEATURES		(1U << 5)
#define ETHTOOL_IM_SETTINGS_PRIVFLAGS		(1U << 6)

#define ETHTOOL_IM_SETTINGS_ALL (ETHTOOL_IM_SETTINGS_LINKINFO | \
				 ETHTOOL_IM_SETTINGS_LINKMODES | \
				 ETHTOOL_IM_SETTINGS_LINKSTATE | \
				 ETHTOOL_IM_SETTINGS_WOL | \
				 ETHTOOL_IM_SETTINGS_DEBUG | \
				 ETHTOOL_IM_SETTINGS_FEATURES | \
				 ETHTOOL_IM_SETTINGS_PRIVFLAGS)

enum {
	ETHTOOL_A_LINKINFO_UNSPEC,
	ETHTOOL_A_LINKINFO_PORT,		/* u8 */
	ETHTOOL_A_LINKINFO_PHYADDR,		/* u8 */
	ETHTOOL_A_LINKINFO_TP_MDIX,		/* u8 */
	ETHTOOL_A_LINKINFO_TP_MDIX_CTRL,	/* u8 */
	ETHTOOL_A_LINKINFO_TRANSCEIVER,		/* u8 */

	__ETHTOOL_A_LINKINFO_CNT,
	ETHTOOL_A_LINKINFO_MAX = (__ETHTOOL_A_LINKINFO_CNT - 1)
};

enum {
	ETHTOOL_A_LINKMODES_UNSPEC,
	ETHTOOL_A_LINKMODES_AUTONEG,		/* u8 */
	ETHTOOL_A_LINKMODES_OURS,		/* bitset */
	ETHTOOL_A_LINKMODES_PEER,		/* bitset */
	ETHTOOL_A_LINKMODES_SPEED,		/* u32 */
	ETHTOOL_A_LINKMODES_DUPLEX,		/* u8 */

	__ETHTOOL_A_LINKMODES_CNT,
	ETHTOOL_A_LINKMODES_MAX = (__ETHTOOL_A_LINKMODES_CNT - 1)
};

enum {
	ETHTOOL_A_LINKSTATE_UNSPEC,
	ETHTOOL_A_LINKSTATE_LINK,		/* u8 */

	__ETHTOOL_A_LINKSTATE_CNT,
	ETHTOOL_A_LINKSTATE_MAX = (__ETHTOOL_A_LINKSTATE_CNT - 1)
};

enum {
	ETHTOOL_A_WOL_UNSPEC,
	ETHTOOL_A_WOL_MODES,			/* bitfield32 */
	ETHTOOL_A_WOL_SOPASS,			/* binary */

	__ETHTOOL_A_WOL_CNT,
	ETHTOOL_A_WOL_MAX = (__ETHTOOL_A_WOL_CNT - 1)
};

enum {
	ETHTOOL_A_DEBUG_UNSPEC,
	ETHTOOL_A_DEBUG_MSG_MASK,		/* bitfield32 */

	__ETHTOOL_A_DEBUG_CNT,
	ETHTOOL_A_DEBUG_MAX = (__ETHTOOL_A_DEBUG_CNT - 1)
};

enum {
	ETHTOOL_A_FEATURES_UNSPEC,
	ETHTOOL_A_FEATURES_HW,			/* bitset */
	ETHTOOL_A_FEATURES_WANTED,		/* bitset */
	ETHTOOL_A_FEATURES_ACTIVE,		/* bitset */
	ETHTOOL_A_FEATURES_NOCHANGE,		/* bitset */
	ETHTOOL_A_FEATURES_WANT_DIFF,		/* flag */

	__ETHTOOL_A_FEATURES_CNT,
	ETHTOOL_A_FEATURES_MAX = (__ETHTOOL_A_FEATURES_CNT - 1)
};

/* GET_PARAMS / SET_PARAMS */

enum {
	ETHTOOL_A_PARAMS_UNSPEC,
	ETHTOOL_A_PARAMS_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_PARAMS_INFOMASK,		/* u32 */
	ETHTOOL_A_PARAMS_COMPACT,		/* flag */
	ETHTOOL_A_PARAMS_COALESCE,		/* nest - ETHTOOL_A_COALESCE_* */
	ETHTOOL_A_PARAMS_RING,			/* nest - ETHTOOL_A_RING_* */
	ETHTOOL_A_PARAMS_PAUSE,			/* nest - ETHTOOL_A_PAUSE_* */
	ETHTOOL_A_PARAMS_CHANNELS,		/* nest - ETHTOOL_A_CHANNELS_* */
	ETHTOOL_A_PARAMS_EEE,			/* nest - ETHTOOL_A_EEE_* */
	ETHTOOL_A_PARAMS_FEC,			/* nest - ETHTOOL_A_FEC_* */

	__ETHTOOL_A_PARAMS_CNT,
	ETHTOOL_A_PARAMS_MAX = (__ETHTOOL_A_PARAMS_CNT - 1)
};

#define ETHTOOL_IM_PARAMS_COALESCE		(1U << 0)
#define ETHTOOL_IM_PARAMS_RING			(1U << 1)
#define ETHTOOL_IM_PARAMS_PAUSE			(1U << 2)
#define ETHTOOL_IM_PARAMS_CHANNELS		(1U << 3)
#define ETHTOOL_IM_PARAMS_EEE			(1U << 4)
#define ETHTOOL_IM_PARAMS_FEC			(1U << 5)

#define ETHTOOL_IM_PARAMS_ALL (ETHTOOL_IM_PARAMS_COALESCE | \
			       ETHTOOL_IM_PARAMS_RING | \
			       ETHTOOL_IM_PARAMS_PAUSE | \
			       ETHTOOL_IM_PARAMS_CHANNELS | \
			       ETHTOOL_IM_PARAMS_EEE | \
			       ETHTOOL_IM_PARAMS_FEC)

enum {
	ETHTOOL_A_COALESCE_UNSPEC,
	ETHTOOL_A_COALESCE_RX_USECS,		/* u32 */
	ETHTOOL_A_COALESCE_RX_MAXFRM,		/* u32 */
	ETHTOOL_A_COALESCE_RX_USECS_IRQ,	/* u32 */
	ETHTOOL_A_COALESCE_RX_MAXFRM_IRQ,	/* u32 */
	ETHTOOL_A_COALESCE_RX_USECS_LOW,	/* u32 */
	ETHTOOL_A_COALESCE_RX_MAXFRM_LOW,	/* u32 */
	ETHTOOL_A_COALESCE_RX_USECS_HIGH,	/* u32 */
	ETHTOOL_A_COALESCE_RX_MAXFRM_HIGH,	/* u32 */
	ETHTOOL_A_COALESCE_TX_USECS,		/* u32 */
	ETHTOOL_A_COALESCE_TX_MAXFRM,		/* u32 */
	ETHTOOL_A_COALESCE_TX_USECS_IRQ,	/* u32 */
	ETHTOOL_A_COALESCE_TX_MAXFRM_IRQ,	/* u32 */
	ETHTOOL_A_COALESCE_TX_USECS_LOW,	/* u32 */
	ETHTOOL_A_COALESCE_TX_MAXFRM_LOW,	/* u32 */
	ETHTOOL_A_COALESCE_TX_USECS_HIGH,	/* u32 */
	ETHTOOL_A_COALESCE_TX_MAXFRM_HIGH,	/* u32 */
	ETHTOOL_A_COALESCE_PKT_RATE_LOW,	/* u32 */
	ETHTOOL_A_COALESCE_PKT_RATE_HIGH,	/* u32 */
	ETHTOOL_A_COALESCE_RX_USE_ADAPTIVE,	/* u8 */
	ETHTOOL_A_COALESCE_TX_USE_ADAPTIVE,	/* u8 */
	ETHTOOL_A_COALESCE_RATE_SAMPLE_INTERVAL, /* u32 */
	ETHTOOL_A_COALESCE_STATS_BLOCK_USECS,	/* u32 */

	__ETHTOOL_A_COALESCE_CNT,
	ETHTOOL_A_COALESCE_MAX = (__ETHTOOL_A_COALESCE_CNT - 1)
};

enum {
	ETHTOOL_A_RING_UNSPEC,
	ETHTOOL_A_RING_RX_MAX_PENDING,		/* u32 */
	ETHTOOL_A_RING_RX_MINI_MAX_PENDING,	/* u32 */
	ETHTOOL_A_RING_RX_JUMBO_MAX_PENDING,	/* u32 */
	ETHTOOL_A_RING_TX_MAX_PENDING,		/* u32 */
	ETHTOOL_A_RING_RX_PENDING,		/* u32 */
	ETHTOOL_A_RING_RX_MINI_PENDING,		/* u32 */
	ETHTOOL_A_RING_RX_JUMBO_PENDING,	/* u32 */
	ETHTOOL_A_RING_TX_PENDING,		/* u32 */

	__ETHTOOL_A_RING_CNT,
	ETHTOOL_A_RING_MAX = (__ETHTOOL_A_RING_CNT - 1)
};

enum {
	ETHTOOL_A_PAUSE_UNSPEC,
	ETHTOOL_A_PAUSE_AUTONEG,		/* u8 */
	ETHTOOL_A_PAUSE_RX,			/* u8 */
	ETHTOOL_A_PAUSE_TX,			/* u8 */

	__ETHTOOL_A_PAUSE_CNT,
	ETHTOOL_A_PAUSE_MAX = (__ETHTOOL_A_PAUSE_CNT - 1)
};

enum {
	ETHTOOL_A_CHANNELS_UNSPEC,
	ETHTOOL_A_CHANNELS_MAX_RX,		/* u32 */
	ETHTOOL_A_CHANNELS_MAX_TX,		/* u32 */
	ETHTOOL_A_CHANNELS_MAX_OTHER,		/* u32 */
	ETHTOOL_A_CHANNELS_MAX_COMBINED,	/* u32 */
	ETHTOOL_A_CHANNELS_RX_COUNT,		/* u32 */
	ETHTOOL_A_CHANNELS_TX_COUNT,		/* u32 */
	ETHTOOL_A_CHANNELS_OTHER_COUNT,		/* u32 */
	ETHTOOL_A_CHANNELS_COMBINED_COUNT,	/* u32 */

	__ETHTOOL_A_CHANNELS_CNT,
	ETHTOOL_A_CHANNELS_MAX = (__ETHTOOL_A_CHANNELS_CNT - 1)
};

enum {
	ETHTOOL_A_EEE_UNSPEC,
	ETHTOOL_A_EEE_LINK_MODES,		/* bitset */
	ETHTOOL_A_EEE_PEER_MODES,		/* bitset */
	ETHTOOL_A_EEE_ACTIVE,			/* u8 */
	ETHTOOL_A_EEE_ENABLED,			/* u8 */
	ETHTOOL_A_EEE_TX_LPI_ENABLED,		/* u8 */
	ETHTOOL_A_EEE_TX_LPI_TIMER,		/* u32 */

	__ETHTOOL_A_EEE_CNT,
	ETHTOOL_A_EEE_MAX = (__ETHTOOL_A_EEE_CNT - 1)
};

enum {
	ETHTOOL_A_FEC_UNSPEC,
	ETHTOOL_A_FEC_MODES,			/* bitfield32 */

	__ETHTOOL_A_FEC_CNT,
	ETHTOOL_A_FEC_MAX = (__ETHTOOL_A_FEC_CNT - 1)
};

/* ACT_NWAY_RST */

enum {
	ETHTOOL_A_NWAYRST_UNSPEC,
	ETHTOOL_A_NWAYRST_DEV,			/* nest - ETHTOOL_A_DEV_* */

	__ETHTOOL_A_NWAYRST_CNT,
	ETHTOOL_A_NWAYRST_MAX = (__ETHTOOL_A_NWAYRST_CNT - 1)
};

/* ACT_PHYS_ID */

enum {
	ETHTOOL_A_PHYSID_UNSPEC,
	ETHTOOL_A_PHYSID_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_PHYSID_LENGTH,		/* u32 */

	__ETHTOOL_A_PHYSID_CNT,
	ETHTOOL_A_PHYSID_MAX = (__ETHTOOL_A_PHYSID_CNT - 1)
};

/* ACT_RESET */

enum {
	ETHTOOL_A_RESET_UNSPEC,
	ETHTOOL_A_RESET_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_RESET_COMPACT,		/* flag */
	ETHTOOL_A_RESET_ALL,			/* flag */
	ETHTOOL_A_RESET_ALL_DEDICATED,		/* flag */
	ETHTOOL_A_RESET_DEDICATED,		/* bitset */
	ETHTOOL_A_RESET_SHARED,			/* bitset */

	__ETHTOOL_A_RESET_CNT,
	ETHTOOL_A_RESET_MAX = (__ETHTOOL_A_RESET_CNT - 1)
};

/* GET_RXFLOW / SET_RXFLOW */

enum {
	ETHTOOL_A_RXFLOW_UNSPEC,
	ETHTOOL_A_RXFLOW_DEV,			/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_RXFLOW_INFOMASK,		/* u32 */
	ETHTOOL_A_RXFLOW_COMPACT,		/* flag */
	ETHTOOL_A_RXFLOW_CTXOP,			/* u32 - ETHTOOL_RXFLOW_CTXOP_* */
	ETHTOOL_A_RXFLOW_CONTEXT,		/* u32 */
	ETHTOOL_A_RXFLOW_NRINGS,		/* u32 */
	ETHTOOL_A_RXFLOW_HASH_FN,		/* bitset */
	ETHTOOL_A_RXFLOW_HASH_KEY,		/* binary */
	ETHTOOL_A_RXFLOW_HASH_OPTS,		/* nest - ETHTOOL_A_RXHASHOPTS_* */
	ETHTOOL_A_RXFLOW_INDTBL_SIZE,		/* u32 */
	ETHTOOL_A_RXFLOW_INDIR_TBL,		/* nest - ETHTOOL_A_INDTBL_* */

	__ETHTOOL_A_RXFLOW_CNT,
	ETHTOOL_A_RXFLOW_MAX = (__ETHTOOL_A_RXFLOW_CNT - 1)
};

#define ETHTOOL_IM_RXFLOW_INFO			(1U << 0)
#define ETHTOOL_IM_RXFLOW_HASHFN		(1U << 1)
#define ETHTOOL_IM_RXFLOW_HKEY			(1U << 2)
#define ETHTOOL_IM_RXFLOW_HASHOPTS		(1U << 3)
#define ETHTOOL_IM_RXFLOW_INDTBL		(1U << 4)

#define ETHTOOL_IM_RXFLOW_ALL (ETHTOOL_IM_RXFLOW_INFO | \
			       ETHTOOL_IM_RXFLOW_HASHFN | \
			       ETHTOOL_IM_RXFLOW_HKEY | \
			       ETHTOOL_IM_RXFLOW_HASHOPTS | \
			       ETHTOOL_IM_RXFLOW_INDTBL)

enum {
	ETHTOOL_RXFLOW_CTXOP_SET,		/* set context data */
	ETHTOOL_RXFLOW_CTXOP_NEW,		/* create new context */
	ETHTOOL_RXFLOW_CTXOP_DEL,		/* delete existing context */
};

enum {
	ETHTOOL_A_RXHASHOPTS_UNSPEC,
	ETHTOOL_A_RXHASHOPTS_OPT,		/* nest - ETH_RXHASHOPT_* */

	__ETHTOOL_A_RXHASHOPTS_CNT,
	ETHTOOL_A_RXHASHOPTS_MAX = (__ETHTOOL_A_RXHASHOPTS_CNT - 1)
};

enum {
	ETHTOOL_A_RXHASHOPT_UNSPEC,
	ETHTOOL_A_RXHASHOPT_FLOWTYPE,		/* u32 */
	ETHTOOL_A_RXHASHOPT_FIELDS,		/* bitfield32 */
	ETHTOOL_A_RXHASHOPT_DISCARD,		/* flag */

	__ETHTOOL_A_RXHASHOPT_CNT,
	ETHTOOL_A_RXHASHOPT_MAX = (__ETHTOOL_A_RXHASHOPT_CNT - 1)
};

/* Cable test CMD_EVENT for reporting results */

enum {
	ETHTOOL_A_CABLE_RESULT_CODE_UNSPEC,
	ETHTOOL_A_CABLE_RESULT_CODE_OK,
	ETHTOOL_A_CABLE_RESULT_CODE_OPEN,
	ETHTOOL_A_CABLE_RESULT_CODE_SAME_SHORT,
	ETHTOOL_A_CABLE_RESULT_CODE_CROSS_SHORT,
};

enum {
	ETHTOOL_A_CABLE_PAIR_0,
	ETHTOOL_A_CABLE_PAIR_1,
	ETHTOOL_A_CABLE_PAIR_2,
	ETHTOOL_A_CABLE_PAIR_3,
};

enum {
	ETHTOOL_A_CABLE_RESULT_UNSPEC,
	ETHTOOL_A_CABLE_RESULT_PAIR,		/* u8 */
	ETHTOOL_A_CABLE_RESULT_CODE,		/* u8 ETHTOOL_A_CABLE_RESULT_CODE_ */

	__ETHTOOL_A_CABLE_RESULT_CNT,
	ETHTOOL_A_CABLE_RESULT_MAX = (__ETHTOOL_A_CABLE_RESULT_CNT - 1)
};

enum {
	ETHTOOL_A_CABLE_FAULT_LENGTH_UNSPEC,
	ETHTOOL_A_CABLE_FAULT_LENGTH_PAIR,	/* u8 */
	ETHTOOL_A_CABLE_FAULT_LENGTH_CM,	/* u16 */

	__ETHTOOL_A_CABLE_FAULT_LENGTH_CNT,
	ETHTOOL_A_CABLE_FAULT_LENGTH_MAX = (__ETHTOOL_A_CABLE_FAULT_LENGTH_CNT - 1)
};

enum {
	ETHTOOL_A_CABLE_LENGTH_UNSPEC,
	ETHTOOL_A_CABLE_LENGTH_PAIR,		/* u8 */
	ETHTOOL_A_CABLE_LENGTH_CM,		/* u16 */

	__ETHTOOL_A_CABLE_LENGTH_CNT,
	ETHTOOL_A_CABLE_LENGTH_MAX = (__ETHTOOL_A_CABLE_LENGTH_CNT - 1)
};

enum {
	ETHTOOL_A_CABLE_TEST_EVENT_UNSPEC,
	ETHTOOL_A_CABLE_TEST_EVENT_DEV,		/* nest - ETHTOOL_A_DEV_* */
	ETHTOOL_A_CABLE_TEST_EVENT_RESULT,	/* nest - ETHTOOL_A_CABLE_RESULT_ */
	ETHTOOL_A_CABLE_TEST_EVENT_FAULT_LENGTH,/* nest - ETHTOOL_A_CABLE_FAULT_LENGTH_ */

	__ETHTOOL_A_CABLE_TEST_EVENT_CNT,
	ETHTOOL_A_CABLE_TEST_EVENT_MAX = (__ETHTOOL_A_CABLE_TEST_EVENT_CNT - 1)
};

/* ACT_CABLE_TEST */

enum {
	ETHTOOL_A_CABLE_TEST_UNSPEC,
	ETHTOOL_A_CABLE_TEST_DEV,		/* nest - ETHTOOL_A_DEV_* */

	__ETHTOOL_A_CABLE_TEST_CNT,
	ETHTOOL_A_CABLE_TEST_MAX = (__ETHTOOL_A_CABLE_TEST_CNT - 1)
};

enum {
	ETHTOOL_A_INDTBL_UNSPEC,
	ETHTOOL_A_INDTBL_BLOCK32,		/* nest - ETH_ITBLK_* */
	ETHTOOL_A_INDTBL_BLOCK16,		/* nest - ETH_ITBLK_* */
	ETHTOOL_A_INDTBL_BLOCK8, 		/* nest - ETH_ITBLK_* */
	ETHTOOL_A_INDTBL_PATTERN,		/* nest - ETH_ITPAT_* */
	ETHTOOL_A_INDTBL_WEIGHTS,		/* nest - ETH_ITWGHT_* */

	__ETHTOOL_A_INDTBL_CNT,
	ETHTOOL_A_INDTBL_MAX = (__ETHTOOL_A_INDTBL_CNT - 1)
};

enum {
	ETHTOOL_A_ITBLK_UNSPEC,
	ETHTOOL_A_ITBLK_START,			/* u32 */
	ETHTOOL_A_ITBLK_LEN,			/* u32 */
	ETHTOOL_A_ITBLK_DATA,			/* binary */

	__ETHTOOL_A_ITBLK_CNT,
	ETHTOOL_A_ITBLK_MAX = (__ETHTOOL_A_ITBLK_CNT - 1)
};

enum {
	ETHTOOL_A_ITPAT_UNSPEC,
	ETHTOOL_A_ITPAT_START,			/* u32 */
	ETHTOOL_A_ITPAT_LEN,			/* u32 */
	ETHTOOL_A_ITPAT_MIN_RING,		/* u32 */
	ETHTOOL_A_ITPAT_MAX_RING,		/* u32 */
	ETHTOOL_A_ITPAT_OFFSET,			/* u32 */

	__ETHTOOL_A_ITPAT_CNT,
	ETHTOOL_A_ITPAT_MAX = (__ETHTOOL_A_ITPAT_CNT - 1)
};

enum {
	ETHTOOL_A_ITWGHT_UNSPEC,
	ETHTOOL_A_ITWGHT_VALUES,		/* binary */
	ETHTOOL_A_ITWGHT_WEIGHTS,		/* binary */

	__ETHTOOL_A_ITWGHT_CNT,
	ETHTOOL_A_ITWGHT_MAX = (__ETHTOOL_A_ITWGHT_CNT - 1)
};

/* generic netlink info */
#define ETHTOOL_GENL_NAME "ethtool"
#define ETHTOOL_GENL_VERSION 1

#define ETHTOOL_MCGRP_MONITOR_NAME "monitor"

#endif /* _UAPI_LINUX_ETHTOOL_NETLINK_H_ */
